#############################################################################
# Makefile for building: ni-translate
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  ni-translate.pro
# Template: app
# Command: /home/yasir/Programs/anaconda3/bin/qmake -o Makefile ni-translate.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../Programs/anaconda3/include/qt -I../../Programs/anaconda3/include/qt/QtWidgets -I../../Programs/anaconda3/include/qt/QtGui -I../../Programs/anaconda3/include/qt/QtCore -I. -I. -I../../Programs/anaconda3/mkspecs/linux-g++
QMAKE         = /home/yasir/Programs/anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/yasir/Programs/anaconda3/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/yasir/Programs/anaconda3/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ni-translate1.0.0
DISTDIR = /home/yasir/Desktop/ni-translate/.tmp/ni-translate1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/yasir/Programs/anaconda3/lib
LIBS          = $(SUBLIBS) -L/home/yasir/Programs/anaconda3/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		keycatcher.cpp \
		utils.cpp moc_mainwindow.cpp \
		moc_keycatcher.cpp
OBJECTS       = main.o \
		mainwindow.o \
		keycatcher.o \
		utils.o \
		moc_mainwindow.o \
		moc_keycatcher.o
DIST          = ../../Programs/anaconda3/mkspecs/features/spec_pre.prf \
		../../Programs/anaconda3/mkspecs/common/unix.conf \
		../../Programs/anaconda3/mkspecs/common/linux.conf \
		../../Programs/anaconda3/mkspecs/common/sanitize.conf \
		../../Programs/anaconda3/mkspecs/common/gcc-base.conf \
		../../Programs/anaconda3/mkspecs/common/gcc-base-unix.conf \
		../../Programs/anaconda3/mkspecs/common/g++-base.conf \
		../../Programs/anaconda3/mkspecs/common/g++-unix.conf \
		../../Programs/anaconda3/mkspecs/qconfig.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_core.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_help.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_location.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_network.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_script.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Programs/anaconda3/mkspecs/features/qt_functions.prf \
		../../Programs/anaconda3/mkspecs/features/qt_config.prf \
		../../Programs/anaconda3/mkspecs/linux-g++/qmake.conf \
		../../Programs/anaconda3/mkspecs/features/spec_post.prf \
		../../Programs/anaconda3/mkspecs/features/exclusive_builds.prf \
		../../Programs/anaconda3/mkspecs/features/toolchain.prf \
		../../Programs/anaconda3/mkspecs/features/default_pre.prf \
		../../Programs/anaconda3/mkspecs/features/resolve_config.prf \
		../../Programs/anaconda3/mkspecs/features/default_post.prf \
		../../Programs/anaconda3/mkspecs/features/warn_on.prf \
		../../Programs/anaconda3/mkspecs/features/qt.prf \
		../../Programs/anaconda3/mkspecs/features/resources.prf \
		../../Programs/anaconda3/mkspecs/features/moc.prf \
		../../Programs/anaconda3/mkspecs/features/unix/opengl.prf \
		../../Programs/anaconda3/mkspecs/features/uic.prf \
		../../Programs/anaconda3/mkspecs/features/unix/thread.prf \
		../../Programs/anaconda3/mkspecs/features/qmake_use.prf \
		../../Programs/anaconda3/mkspecs/features/file_copies.prf \
		../../Programs/anaconda3/mkspecs/features/testcase_targets.prf \
		../../Programs/anaconda3/mkspecs/features/exceptions.prf \
		../../Programs/anaconda3/mkspecs/features/yacc.prf \
		../../Programs/anaconda3/mkspecs/features/lex.prf \
		ni-translate.pro mainwindow.h \
		keycatcher.h \
		utils.h main.cpp \
		mainwindow.cpp \
		keycatcher.cpp \
		utils.cpp
QMAKE_TARGET  = ni-translate
DESTDIR       = 
TARGET        = ni-translate


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ni-translate.pro ../../Programs/anaconda3/mkspecs/linux-g++/qmake.conf ../../Programs/anaconda3/mkspecs/features/spec_pre.prf \
		../../Programs/anaconda3/mkspecs/common/unix.conf \
		../../Programs/anaconda3/mkspecs/common/linux.conf \
		../../Programs/anaconda3/mkspecs/common/sanitize.conf \
		../../Programs/anaconda3/mkspecs/common/gcc-base.conf \
		../../Programs/anaconda3/mkspecs/common/gcc-base-unix.conf \
		../../Programs/anaconda3/mkspecs/common/g++-base.conf \
		../../Programs/anaconda3/mkspecs/common/g++-unix.conf \
		../../Programs/anaconda3/mkspecs/qconfig.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_core.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_help.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_location.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_network.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_script.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Programs/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Programs/anaconda3/mkspecs/features/qt_functions.prf \
		../../Programs/anaconda3/mkspecs/features/qt_config.prf \
		../../Programs/anaconda3/mkspecs/linux-g++/qmake.conf \
		../../Programs/anaconda3/mkspecs/features/spec_post.prf \
		../../Programs/anaconda3/mkspecs/features/exclusive_builds.prf \
		../../Programs/anaconda3/mkspecs/features/toolchain.prf \
		../../Programs/anaconda3/mkspecs/features/default_pre.prf \
		../../Programs/anaconda3/mkspecs/features/resolve_config.prf \
		../../Programs/anaconda3/mkspecs/features/default_post.prf \
		../../Programs/anaconda3/mkspecs/features/warn_on.prf \
		../../Programs/anaconda3/mkspecs/features/qt.prf \
		../../Programs/anaconda3/mkspecs/features/resources.prf \
		../../Programs/anaconda3/mkspecs/features/moc.prf \
		../../Programs/anaconda3/mkspecs/features/unix/opengl.prf \
		../../Programs/anaconda3/mkspecs/features/uic.prf \
		../../Programs/anaconda3/mkspecs/features/unix/thread.prf \
		../../Programs/anaconda3/mkspecs/features/qmake_use.prf \
		../../Programs/anaconda3/mkspecs/features/file_copies.prf \
		../../Programs/anaconda3/mkspecs/features/testcase_targets.prf \
		../../Programs/anaconda3/mkspecs/features/exceptions.prf \
		../../Programs/anaconda3/mkspecs/features/yacc.prf \
		../../Programs/anaconda3/mkspecs/features/lex.prf \
		ni-translate.pro \
		../../Programs/anaconda3/lib/libQt5Widgets.prl \
		../../Programs/anaconda3/lib/libQt5Gui.prl \
		../../Programs/anaconda3/lib/libQt5Core.prl
	$(QMAKE) -o Makefile ni-translate.pro -spec linux-g++
../../Programs/anaconda3/mkspecs/features/spec_pre.prf:
../../Programs/anaconda3/mkspecs/common/unix.conf:
../../Programs/anaconda3/mkspecs/common/linux.conf:
../../Programs/anaconda3/mkspecs/common/sanitize.conf:
../../Programs/anaconda3/mkspecs/common/gcc-base.conf:
../../Programs/anaconda3/mkspecs/common/gcc-base-unix.conf:
../../Programs/anaconda3/mkspecs/common/g++-base.conf:
../../Programs/anaconda3/mkspecs/common/g++-unix.conf:
../../Programs/anaconda3/mkspecs/qconfig.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3drender.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_charts.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_core.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_core_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_dbus.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_designer.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_gui.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_help.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_help_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_input_support_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_location.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_location_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_network.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_network_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_nfc.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_opengl.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_positioning.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_qml.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_quick.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_repparser.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_script.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_script_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_scxml.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_sensors.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_serialport.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_service_support_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_sql.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_svg.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_testlib.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_uitools.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_webengine.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_websockets.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_webview.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_widgets.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_x11extras.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_xml.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Programs/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Programs/anaconda3/mkspecs/features/qt_functions.prf:
../../Programs/anaconda3/mkspecs/features/qt_config.prf:
../../Programs/anaconda3/mkspecs/linux-g++/qmake.conf:
../../Programs/anaconda3/mkspecs/features/spec_post.prf:
../../Programs/anaconda3/mkspecs/features/exclusive_builds.prf:
../../Programs/anaconda3/mkspecs/features/toolchain.prf:
../../Programs/anaconda3/mkspecs/features/default_pre.prf:
../../Programs/anaconda3/mkspecs/features/resolve_config.prf:
../../Programs/anaconda3/mkspecs/features/default_post.prf:
../../Programs/anaconda3/mkspecs/features/warn_on.prf:
../../Programs/anaconda3/mkspecs/features/qt.prf:
../../Programs/anaconda3/mkspecs/features/resources.prf:
../../Programs/anaconda3/mkspecs/features/moc.prf:
../../Programs/anaconda3/mkspecs/features/unix/opengl.prf:
../../Programs/anaconda3/mkspecs/features/uic.prf:
../../Programs/anaconda3/mkspecs/features/unix/thread.prf:
../../Programs/anaconda3/mkspecs/features/qmake_use.prf:
../../Programs/anaconda3/mkspecs/features/file_copies.prf:
../../Programs/anaconda3/mkspecs/features/testcase_targets.prf:
../../Programs/anaconda3/mkspecs/features/exceptions.prf:
../../Programs/anaconda3/mkspecs/features/yacc.prf:
../../Programs/anaconda3/mkspecs/features/lex.prf:
ni-translate.pro:
../../Programs/anaconda3/lib/libQt5Widgets.prl:
../../Programs/anaconda3/lib/libQt5Gui.prl:
../../Programs/anaconda3/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ni-translate.pro -spec linux-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Programs/anaconda3/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h keycatcher.h utils.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp keycatcher.cpp utils.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Programs/anaconda3/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h ../../Programs/anaconda3/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_keycatcher.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_keycatcher.cpp
moc_mainwindow.cpp: ../../Programs/anaconda3/include/qt/QtWidgets/QMainWindow \
		../../Programs/anaconda3/include/qt/QtWidgets/qmainwindow.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../Programs/anaconda3/include/qt/QtGui/qtguiglobal.h \
		../../Programs/anaconda3/include/qt/QtCore/qglobal.h \
		../../Programs/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../../Programs/anaconda3/include/qt/QtCore/qconfig.h \
		../../Programs/anaconda3/include/qt/QtCore/qtcore-config.h \
		../../Programs/anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../Programs/anaconda3/include/qt/QtCore/qsysinfo.h \
		../../Programs/anaconda3/include/qt/QtCore/qlogging.h \
		../../Programs/anaconda3/include/qt/QtCore/qflags.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../Programs/anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../Programs/anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../Programs/anaconda3/include/qt/QtCore/qmutex.h \
		../../Programs/anaconda3/include/qt/QtCore/qnumeric.h \
		../../Programs/anaconda3/include/qt/QtCore/qversiontagging.h \
		../../Programs/anaconda3/include/qt/QtGui/qtgui-config.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qwidget.h \
		../../Programs/anaconda3/include/qt/QtGui/qwindowdefs.h \
		../../Programs/anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../Programs/anaconda3/include/qt/QtCore/qnamespace.h \
		../../Programs/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../Programs/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../../Programs/anaconda3/include/qt/QtCore/qobject.h \
		../../Programs/anaconda3/include/qt/QtCore/qstring.h \
		../../Programs/anaconda3/include/qt/QtCore/qchar.h \
		../../Programs/anaconda3/include/qt/QtCore/qbytearray.h \
		../../Programs/anaconda3/include/qt/QtCore/qrefcount.h \
		../../Programs/anaconda3/include/qt/QtCore/qarraydata.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../Programs/anaconda3/include/qt/QtCore/qlist.h \
		../../Programs/anaconda3/include/qt/QtCore/qalgorithms.h \
		../../Programs/anaconda3/include/qt/QtCore/qiterator.h \
		../../Programs/anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../Programs/anaconda3/include/qt/QtCore/qpair.h \
		../../Programs/anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringlist.h \
		../../Programs/anaconda3/include/qt/QtCore/qregexp.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../Programs/anaconda3/include/qt/QtCore/qcoreevent.h \
		../../Programs/anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../Programs/anaconda3/include/qt/QtCore/qmetatype.h \
		../../Programs/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../Programs/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../Programs/anaconda3/include/qt/QtCore/qobject_impl.h \
		../../Programs/anaconda3/include/qt/QtCore/qmargins.h \
		../../Programs/anaconda3/include/qt/QtGui/qpaintdevice.h \
		../../Programs/anaconda3/include/qt/QtCore/qrect.h \
		../../Programs/anaconda3/include/qt/QtCore/qsize.h \
		../../Programs/anaconda3/include/qt/QtCore/qpoint.h \
		../../Programs/anaconda3/include/qt/QtGui/qpalette.h \
		../../Programs/anaconda3/include/qt/QtGui/qcolor.h \
		../../Programs/anaconda3/include/qt/QtGui/qrgb.h \
		../../Programs/anaconda3/include/qt/QtGui/qrgba64.h \
		../../Programs/anaconda3/include/qt/QtGui/qbrush.h \
		../../Programs/anaconda3/include/qt/QtCore/qvector.h \
		../../Programs/anaconda3/include/qt/QtGui/qmatrix.h \
		../../Programs/anaconda3/include/qt/QtGui/qpolygon.h \
		../../Programs/anaconda3/include/qt/QtGui/qregion.h \
		../../Programs/anaconda3/include/qt/QtCore/qdatastream.h \
		../../Programs/anaconda3/include/qt/QtCore/qiodevice.h \
		../../Programs/anaconda3/include/qt/QtCore/qline.h \
		../../Programs/anaconda3/include/qt/QtGui/qtransform.h \
		../../Programs/anaconda3/include/qt/QtGui/qpainterpath.h \
		../../Programs/anaconda3/include/qt/QtGui/qimage.h \
		../../Programs/anaconda3/include/qt/QtGui/qpixelformat.h \
		../../Programs/anaconda3/include/qt/QtGui/qpixmap.h \
		../../Programs/anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../Programs/anaconda3/include/qt/QtCore/qshareddata.h \
		../../Programs/anaconda3/include/qt/QtCore/qhash.h \
		../../Programs/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../../Programs/anaconda3/include/qt/QtGui/qfont.h \
		../../Programs/anaconda3/include/qt/QtGui/qfontmetrics.h \
		../../Programs/anaconda3/include/qt/QtGui/qfontinfo.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../../Programs/anaconda3/include/qt/QtGui/qcursor.h \
		../../Programs/anaconda3/include/qt/QtGui/qkeysequence.h \
		../../Programs/anaconda3/include/qt/QtGui/qevent.h \
		../../Programs/anaconda3/include/qt/QtCore/qvariant.h \
		../../Programs/anaconda3/include/qt/QtCore/qmap.h \
		../../Programs/anaconda3/include/qt/QtCore/qdebug.h \
		../../Programs/anaconda3/include/qt/QtCore/qtextstream.h \
		../../Programs/anaconda3/include/qt/QtCore/qlocale.h \
		../../Programs/anaconda3/include/qt/QtCore/qset.h \
		../../Programs/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../Programs/anaconda3/include/qt/QtCore/qurl.h \
		../../Programs/anaconda3/include/qt/QtCore/qurlquery.h \
		../../Programs/anaconda3/include/qt/QtCore/qfile.h \
		../../Programs/anaconda3/include/qt/QtCore/qfiledevice.h \
		../../Programs/anaconda3/include/qt/QtGui/qvector2d.h \
		../../Programs/anaconda3/include/qt/QtGui/qtouchdevice.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qtabwidget.h \
		../../Programs/anaconda3/include/qt/QtGui/qicon.h \
		../../Programs/anaconda3/include/qt/QtCore/QMap \
		mainwindow.h \
		moc_predefs.h \
		../../Programs/anaconda3/bin/moc
	/home/yasir/Programs/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/yasir/Programs/anaconda3/mkspecs/linux-g++ -I/home/yasir/Desktop/ni-translate -I/home/yasir/Programs/anaconda3/include/qt -I/home/yasir/Programs/anaconda3/include/qt/QtWidgets -I/home/yasir/Programs/anaconda3/include/qt/QtGui -I/home/yasir/Programs/anaconda3/include/qt/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_keycatcher.cpp: ../../Programs/anaconda3/include/qt/QtCore/QObject \
		../../Programs/anaconda3/include/qt/QtCore/qobject.h \
		../../Programs/anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../Programs/anaconda3/include/qt/QtCore/qnamespace.h \
		../../Programs/anaconda3/include/qt/QtCore/qglobal.h \
		../../Programs/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../../Programs/anaconda3/include/qt/QtCore/qconfig.h \
		../../Programs/anaconda3/include/qt/QtCore/qtcore-config.h \
		../../Programs/anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../Programs/anaconda3/include/qt/QtCore/qsysinfo.h \
		../../Programs/anaconda3/include/qt/QtCore/qlogging.h \
		../../Programs/anaconda3/include/qt/QtCore/qflags.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../Programs/anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../Programs/anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../Programs/anaconda3/include/qt/QtCore/qmutex.h \
		../../Programs/anaconda3/include/qt/QtCore/qnumeric.h \
		../../Programs/anaconda3/include/qt/QtCore/qversiontagging.h \
		../../Programs/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../Programs/anaconda3/include/qt/QtCore/qstring.h \
		../../Programs/anaconda3/include/qt/QtCore/qchar.h \
		../../Programs/anaconda3/include/qt/QtCore/qbytearray.h \
		../../Programs/anaconda3/include/qt/QtCore/qrefcount.h \
		../../Programs/anaconda3/include/qt/QtCore/qarraydata.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../Programs/anaconda3/include/qt/QtCore/qlist.h \
		../../Programs/anaconda3/include/qt/QtCore/qalgorithms.h \
		../../Programs/anaconda3/include/qt/QtCore/qiterator.h \
		../../Programs/anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../Programs/anaconda3/include/qt/QtCore/qpair.h \
		../../Programs/anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringlist.h \
		../../Programs/anaconda3/include/qt/QtCore/qregexp.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../Programs/anaconda3/include/qt/QtCore/qcoreevent.h \
		../../Programs/anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../Programs/anaconda3/include/qt/QtCore/qmetatype.h \
		../../Programs/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../Programs/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../Programs/anaconda3/include/qt/QtCore/qobject_impl.h \
		keycatcher.h \
		moc_predefs.h \
		../../Programs/anaconda3/bin/moc
	/home/yasir/Programs/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/yasir/Programs/anaconda3/mkspecs/linux-g++ -I/home/yasir/Desktop/ni-translate -I/home/yasir/Programs/anaconda3/include/qt -I/home/yasir/Programs/anaconda3/include/qt/QtWidgets -I/home/yasir/Programs/anaconda3/include/qt/QtGui -I/home/yasir/Programs/anaconda3/include/qt/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include keycatcher.h -o moc_keycatcher.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../Programs/anaconda3/bin/uic
	/home/yasir/Programs/anaconda3/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../Programs/anaconda3/include/qt/QtWidgets/QMainWindow \
		../../Programs/anaconda3/include/qt/QtWidgets/qmainwindow.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../Programs/anaconda3/include/qt/QtGui/qtguiglobal.h \
		../../Programs/anaconda3/include/qt/QtCore/qglobal.h \
		../../Programs/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../../Programs/anaconda3/include/qt/QtCore/qconfig.h \
		../../Programs/anaconda3/include/qt/QtCore/qtcore-config.h \
		../../Programs/anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../Programs/anaconda3/include/qt/QtCore/qsysinfo.h \
		../../Programs/anaconda3/include/qt/QtCore/qlogging.h \
		../../Programs/anaconda3/include/qt/QtCore/qflags.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../Programs/anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../Programs/anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../Programs/anaconda3/include/qt/QtCore/qmutex.h \
		../../Programs/anaconda3/include/qt/QtCore/qnumeric.h \
		../../Programs/anaconda3/include/qt/QtCore/qversiontagging.h \
		../../Programs/anaconda3/include/qt/QtGui/qtgui-config.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qwidget.h \
		../../Programs/anaconda3/include/qt/QtGui/qwindowdefs.h \
		../../Programs/anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../Programs/anaconda3/include/qt/QtCore/qnamespace.h \
		../../Programs/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../Programs/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../../Programs/anaconda3/include/qt/QtCore/qobject.h \
		../../Programs/anaconda3/include/qt/QtCore/qstring.h \
		../../Programs/anaconda3/include/qt/QtCore/qchar.h \
		../../Programs/anaconda3/include/qt/QtCore/qbytearray.h \
		../../Programs/anaconda3/include/qt/QtCore/qrefcount.h \
		../../Programs/anaconda3/include/qt/QtCore/qarraydata.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../Programs/anaconda3/include/qt/QtCore/qlist.h \
		../../Programs/anaconda3/include/qt/QtCore/qalgorithms.h \
		../../Programs/anaconda3/include/qt/QtCore/qiterator.h \
		../../Programs/anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../Programs/anaconda3/include/qt/QtCore/qpair.h \
		../../Programs/anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringlist.h \
		../../Programs/anaconda3/include/qt/QtCore/qregexp.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../Programs/anaconda3/include/qt/QtCore/qcoreevent.h \
		../../Programs/anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../Programs/anaconda3/include/qt/QtCore/qmetatype.h \
		../../Programs/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../Programs/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../Programs/anaconda3/include/qt/QtCore/qobject_impl.h \
		../../Programs/anaconda3/include/qt/QtCore/qmargins.h \
		../../Programs/anaconda3/include/qt/QtGui/qpaintdevice.h \
		../../Programs/anaconda3/include/qt/QtCore/qrect.h \
		../../Programs/anaconda3/include/qt/QtCore/qsize.h \
		../../Programs/anaconda3/include/qt/QtCore/qpoint.h \
		../../Programs/anaconda3/include/qt/QtGui/qpalette.h \
		../../Programs/anaconda3/include/qt/QtGui/qcolor.h \
		../../Programs/anaconda3/include/qt/QtGui/qrgb.h \
		../../Programs/anaconda3/include/qt/QtGui/qrgba64.h \
		../../Programs/anaconda3/include/qt/QtGui/qbrush.h \
		../../Programs/anaconda3/include/qt/QtCore/qvector.h \
		../../Programs/anaconda3/include/qt/QtGui/qmatrix.h \
		../../Programs/anaconda3/include/qt/QtGui/qpolygon.h \
		../../Programs/anaconda3/include/qt/QtGui/qregion.h \
		../../Programs/anaconda3/include/qt/QtCore/qdatastream.h \
		../../Programs/anaconda3/include/qt/QtCore/qiodevice.h \
		../../Programs/anaconda3/include/qt/QtCore/qline.h \
		../../Programs/anaconda3/include/qt/QtGui/qtransform.h \
		../../Programs/anaconda3/include/qt/QtGui/qpainterpath.h \
		../../Programs/anaconda3/include/qt/QtGui/qimage.h \
		../../Programs/anaconda3/include/qt/QtGui/qpixelformat.h \
		../../Programs/anaconda3/include/qt/QtGui/qpixmap.h \
		../../Programs/anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../Programs/anaconda3/include/qt/QtCore/qshareddata.h \
		../../Programs/anaconda3/include/qt/QtCore/qhash.h \
		../../Programs/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../../Programs/anaconda3/include/qt/QtGui/qfont.h \
		../../Programs/anaconda3/include/qt/QtGui/qfontmetrics.h \
		../../Programs/anaconda3/include/qt/QtGui/qfontinfo.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../../Programs/anaconda3/include/qt/QtGui/qcursor.h \
		../../Programs/anaconda3/include/qt/QtGui/qkeysequence.h \
		../../Programs/anaconda3/include/qt/QtGui/qevent.h \
		../../Programs/anaconda3/include/qt/QtCore/qvariant.h \
		../../Programs/anaconda3/include/qt/QtCore/qmap.h \
		../../Programs/anaconda3/include/qt/QtCore/qdebug.h \
		../../Programs/anaconda3/include/qt/QtCore/qtextstream.h \
		../../Programs/anaconda3/include/qt/QtCore/qlocale.h \
		../../Programs/anaconda3/include/qt/QtCore/qset.h \
		../../Programs/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../Programs/anaconda3/include/qt/QtCore/qurl.h \
		../../Programs/anaconda3/include/qt/QtCore/qurlquery.h \
		../../Programs/anaconda3/include/qt/QtCore/qfile.h \
		../../Programs/anaconda3/include/qt/QtCore/qfiledevice.h \
		../../Programs/anaconda3/include/qt/QtGui/qvector2d.h \
		../../Programs/anaconda3/include/qt/QtGui/qtouchdevice.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qtabwidget.h \
		../../Programs/anaconda3/include/qt/QtGui/qicon.h \
		../../Programs/anaconda3/include/qt/QtCore/QMap \
		../../Programs/anaconda3/include/qt/QtWidgets/QApplication \
		../../Programs/anaconda3/include/qt/QtWidgets/qapplication.h \
		../../Programs/anaconda3/include/qt/QtCore/qcoreapplication.h \
		../../Programs/anaconda3/include/qt/QtCore/qeventloop.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		../../Programs/anaconda3/include/qt/QtGui/qguiapplication.h \
		../../Programs/anaconda3/include/qt/QtGui/qinputmethod.h \
		../../Programs/anaconda3/include/qt/QtCore/QSettings \
		../../Programs/anaconda3/include/qt/QtCore/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Programs/anaconda3/include/qt/QtWidgets/QMainWindow \
		../../Programs/anaconda3/include/qt/QtWidgets/qmainwindow.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../Programs/anaconda3/include/qt/QtGui/qtguiglobal.h \
		../../Programs/anaconda3/include/qt/QtCore/qglobal.h \
		../../Programs/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../../Programs/anaconda3/include/qt/QtCore/qconfig.h \
		../../Programs/anaconda3/include/qt/QtCore/qtcore-config.h \
		../../Programs/anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../Programs/anaconda3/include/qt/QtCore/qsysinfo.h \
		../../Programs/anaconda3/include/qt/QtCore/qlogging.h \
		../../Programs/anaconda3/include/qt/QtCore/qflags.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../Programs/anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../Programs/anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../Programs/anaconda3/include/qt/QtCore/qmutex.h \
		../../Programs/anaconda3/include/qt/QtCore/qnumeric.h \
		../../Programs/anaconda3/include/qt/QtCore/qversiontagging.h \
		../../Programs/anaconda3/include/qt/QtGui/qtgui-config.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qwidget.h \
		../../Programs/anaconda3/include/qt/QtGui/qwindowdefs.h \
		../../Programs/anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../Programs/anaconda3/include/qt/QtCore/qnamespace.h \
		../../Programs/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../Programs/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../../Programs/anaconda3/include/qt/QtCore/qobject.h \
		../../Programs/anaconda3/include/qt/QtCore/qstring.h \
		../../Programs/anaconda3/include/qt/QtCore/qchar.h \
		../../Programs/anaconda3/include/qt/QtCore/qbytearray.h \
		../../Programs/anaconda3/include/qt/QtCore/qrefcount.h \
		../../Programs/anaconda3/include/qt/QtCore/qarraydata.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../Programs/anaconda3/include/qt/QtCore/qlist.h \
		../../Programs/anaconda3/include/qt/QtCore/qalgorithms.h \
		../../Programs/anaconda3/include/qt/QtCore/qiterator.h \
		../../Programs/anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../Programs/anaconda3/include/qt/QtCore/qpair.h \
		../../Programs/anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringlist.h \
		../../Programs/anaconda3/include/qt/QtCore/qregexp.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../Programs/anaconda3/include/qt/QtCore/qcoreevent.h \
		../../Programs/anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../Programs/anaconda3/include/qt/QtCore/qmetatype.h \
		../../Programs/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../Programs/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../Programs/anaconda3/include/qt/QtCore/qobject_impl.h \
		../../Programs/anaconda3/include/qt/QtCore/qmargins.h \
		../../Programs/anaconda3/include/qt/QtGui/qpaintdevice.h \
		../../Programs/anaconda3/include/qt/QtCore/qrect.h \
		../../Programs/anaconda3/include/qt/QtCore/qsize.h \
		../../Programs/anaconda3/include/qt/QtCore/qpoint.h \
		../../Programs/anaconda3/include/qt/QtGui/qpalette.h \
		../../Programs/anaconda3/include/qt/QtGui/qcolor.h \
		../../Programs/anaconda3/include/qt/QtGui/qrgb.h \
		../../Programs/anaconda3/include/qt/QtGui/qrgba64.h \
		../../Programs/anaconda3/include/qt/QtGui/qbrush.h \
		../../Programs/anaconda3/include/qt/QtCore/qvector.h \
		../../Programs/anaconda3/include/qt/QtGui/qmatrix.h \
		../../Programs/anaconda3/include/qt/QtGui/qpolygon.h \
		../../Programs/anaconda3/include/qt/QtGui/qregion.h \
		../../Programs/anaconda3/include/qt/QtCore/qdatastream.h \
		../../Programs/anaconda3/include/qt/QtCore/qiodevice.h \
		../../Programs/anaconda3/include/qt/QtCore/qline.h \
		../../Programs/anaconda3/include/qt/QtGui/qtransform.h \
		../../Programs/anaconda3/include/qt/QtGui/qpainterpath.h \
		../../Programs/anaconda3/include/qt/QtGui/qimage.h \
		../../Programs/anaconda3/include/qt/QtGui/qpixelformat.h \
		../../Programs/anaconda3/include/qt/QtGui/qpixmap.h \
		../../Programs/anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../Programs/anaconda3/include/qt/QtCore/qshareddata.h \
		../../Programs/anaconda3/include/qt/QtCore/qhash.h \
		../../Programs/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../../Programs/anaconda3/include/qt/QtGui/qfont.h \
		../../Programs/anaconda3/include/qt/QtGui/qfontmetrics.h \
		../../Programs/anaconda3/include/qt/QtGui/qfontinfo.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../../Programs/anaconda3/include/qt/QtGui/qcursor.h \
		../../Programs/anaconda3/include/qt/QtGui/qkeysequence.h \
		../../Programs/anaconda3/include/qt/QtGui/qevent.h \
		../../Programs/anaconda3/include/qt/QtCore/qvariant.h \
		../../Programs/anaconda3/include/qt/QtCore/qmap.h \
		../../Programs/anaconda3/include/qt/QtCore/qdebug.h \
		../../Programs/anaconda3/include/qt/QtCore/qtextstream.h \
		../../Programs/anaconda3/include/qt/QtCore/qlocale.h \
		../../Programs/anaconda3/include/qt/QtCore/qset.h \
		../../Programs/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../Programs/anaconda3/include/qt/QtCore/qurl.h \
		../../Programs/anaconda3/include/qt/QtCore/qurlquery.h \
		../../Programs/anaconda3/include/qt/QtCore/qfile.h \
		../../Programs/anaconda3/include/qt/QtCore/qfiledevice.h \
		../../Programs/anaconda3/include/qt/QtGui/qvector2d.h \
		../../Programs/anaconda3/include/qt/QtGui/qtouchdevice.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qtabwidget.h \
		../../Programs/anaconda3/include/qt/QtGui/qicon.h \
		../../Programs/anaconda3/include/qt/QtCore/QMap \
		ui_mainwindow.h \
		../../Programs/anaconda3/include/qt/QtCore/QThread \
		../../Programs/anaconda3/include/qt/QtCore/qthread.h \
		../../Programs/anaconda3/include/qt/QtWidgets/QApplication \
		../../Programs/anaconda3/include/qt/QtWidgets/qapplication.h \
		../../Programs/anaconda3/include/qt/QtCore/qcoreapplication.h \
		../../Programs/anaconda3/include/qt/QtCore/qeventloop.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		../../Programs/anaconda3/include/qt/QtGui/qguiapplication.h \
		../../Programs/anaconda3/include/qt/QtGui/qinputmethod.h \
		../../Programs/anaconda3/include/qt/QtGui/QClipboard \
		../../Programs/anaconda3/include/qt/QtGui/qclipboard.h \
		keycatcher.h \
		../../Programs/anaconda3/include/qt/QtCore/QObject \
		utils.h \
		../../Programs/anaconda3/include/qt/QtCore/QDebug \
		../../Programs/anaconda3/include/qt/QtCore/QSettings \
		../../Programs/anaconda3/include/qt/QtCore/qsettings.h \
		../../Programs/anaconda3/include/qt/QtCore/QStringList \
		../../Programs/anaconda3/include/qt/QtCore/QProcess \
		../../Programs/anaconda3/include/qt/QtCore/qprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

keycatcher.o: keycatcher.cpp keycatcher.h \
		../../Programs/anaconda3/include/qt/QtCore/QObject \
		../../Programs/anaconda3/include/qt/QtCore/qobject.h \
		../../Programs/anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../Programs/anaconda3/include/qt/QtCore/qnamespace.h \
		../../Programs/anaconda3/include/qt/QtCore/qglobal.h \
		../../Programs/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../../Programs/anaconda3/include/qt/QtCore/qconfig.h \
		../../Programs/anaconda3/include/qt/QtCore/qtcore-config.h \
		../../Programs/anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../Programs/anaconda3/include/qt/QtCore/qsysinfo.h \
		../../Programs/anaconda3/include/qt/QtCore/qlogging.h \
		../../Programs/anaconda3/include/qt/QtCore/qflags.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../Programs/anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../Programs/anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../Programs/anaconda3/include/qt/QtCore/qmutex.h \
		../../Programs/anaconda3/include/qt/QtCore/qnumeric.h \
		../../Programs/anaconda3/include/qt/QtCore/qversiontagging.h \
		../../Programs/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../Programs/anaconda3/include/qt/QtCore/qstring.h \
		../../Programs/anaconda3/include/qt/QtCore/qchar.h \
		../../Programs/anaconda3/include/qt/QtCore/qbytearray.h \
		../../Programs/anaconda3/include/qt/QtCore/qrefcount.h \
		../../Programs/anaconda3/include/qt/QtCore/qarraydata.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../Programs/anaconda3/include/qt/QtCore/qlist.h \
		../../Programs/anaconda3/include/qt/QtCore/qalgorithms.h \
		../../Programs/anaconda3/include/qt/QtCore/qiterator.h \
		../../Programs/anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../Programs/anaconda3/include/qt/QtCore/qpair.h \
		../../Programs/anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringlist.h \
		../../Programs/anaconda3/include/qt/QtCore/qregexp.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../Programs/anaconda3/include/qt/QtCore/qcoreevent.h \
		../../Programs/anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../Programs/anaconda3/include/qt/QtCore/qmetatype.h \
		../../Programs/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../Programs/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../Programs/anaconda3/include/qt/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keycatcher.o keycatcher.cpp

utils.o: utils.cpp utils.h \
		../../Programs/anaconda3/include/qt/QtCore/QMap \
		../../Programs/anaconda3/include/qt/QtCore/qmap.h \
		../../Programs/anaconda3/include/qt/QtCore/qiterator.h \
		../../Programs/anaconda3/include/qt/QtCore/qglobal.h \
		../../Programs/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../../Programs/anaconda3/include/qt/QtCore/qconfig.h \
		../../Programs/anaconda3/include/qt/QtCore/qtcore-config.h \
		../../Programs/anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../Programs/anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../Programs/anaconda3/include/qt/QtCore/qsysinfo.h \
		../../Programs/anaconda3/include/qt/QtCore/qlogging.h \
		../../Programs/anaconda3/include/qt/QtCore/qflags.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../Programs/anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../Programs/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../Programs/anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../Programs/anaconda3/include/qt/QtCore/qmutex.h \
		../../Programs/anaconda3/include/qt/QtCore/qnumeric.h \
		../../Programs/anaconda3/include/qt/QtCore/qversiontagging.h \
		../../Programs/anaconda3/include/qt/QtCore/qlist.h \
		../../Programs/anaconda3/include/qt/QtCore/qalgorithms.h \
		../../Programs/anaconda3/include/qt/QtCore/qrefcount.h \
		../../Programs/anaconda3/include/qt/QtCore/qarraydata.h \
		../../Programs/anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../Programs/anaconda3/include/qt/QtCore/qchar.h \
		../../Programs/anaconda3/include/qt/QtCore/qpair.h \
		../../Programs/anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../Programs/anaconda3/include/qt/QtCore/qbytearray.h \
		../../Programs/anaconda3/include/qt/QtCore/qnamespace.h \
		../../Programs/anaconda3/include/qt/QtCore/qstring.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringlist.h \
		../../Programs/anaconda3/include/qt/QtCore/qregexp.h \
		../../Programs/anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../Programs/anaconda3/include/qt/QtCore/qdebug.h \
		../../Programs/anaconda3/include/qt/QtCore/qhash.h \
		../../Programs/anaconda3/include/qt/QtCore/qtextstream.h \
		../../Programs/anaconda3/include/qt/QtCore/qiodevice.h \
		../../Programs/anaconda3/include/qt/QtCore/qobject.h \
		../../Programs/anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../Programs/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../Programs/anaconda3/include/qt/QtCore/qcoreevent.h \
		../../Programs/anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../Programs/anaconda3/include/qt/QtCore/qmetatype.h \
		../../Programs/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../Programs/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../Programs/anaconda3/include/qt/QtCore/qobject_impl.h \
		../../Programs/anaconda3/include/qt/QtCore/qlocale.h \
		../../Programs/anaconda3/include/qt/QtCore/qvariant.h \
		../../Programs/anaconda3/include/qt/QtCore/qshareddata.h \
		../../Programs/anaconda3/include/qt/QtCore/qvector.h \
		../../Programs/anaconda3/include/qt/QtCore/qpoint.h \
		../../Programs/anaconda3/include/qt/QtCore/qset.h \
		../../Programs/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../Programs/anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../Programs/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		mainwindow.h \
		../../Programs/anaconda3/include/qt/QtWidgets/QMainWindow \
		../../Programs/anaconda3/include/qt/QtWidgets/qmainwindow.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../Programs/anaconda3/include/qt/QtGui/qtguiglobal.h \
		../../Programs/anaconda3/include/qt/QtGui/qtgui-config.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qwidget.h \
		../../Programs/anaconda3/include/qt/QtGui/qwindowdefs.h \
		../../Programs/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../../Programs/anaconda3/include/qt/QtCore/qmargins.h \
		../../Programs/anaconda3/include/qt/QtGui/qpaintdevice.h \
		../../Programs/anaconda3/include/qt/QtCore/qrect.h \
		../../Programs/anaconda3/include/qt/QtCore/qsize.h \
		../../Programs/anaconda3/include/qt/QtGui/qpalette.h \
		../../Programs/anaconda3/include/qt/QtGui/qcolor.h \
		../../Programs/anaconda3/include/qt/QtGui/qrgb.h \
		../../Programs/anaconda3/include/qt/QtGui/qrgba64.h \
		../../Programs/anaconda3/include/qt/QtGui/qbrush.h \
		../../Programs/anaconda3/include/qt/QtGui/qmatrix.h \
		../../Programs/anaconda3/include/qt/QtGui/qpolygon.h \
		../../Programs/anaconda3/include/qt/QtGui/qregion.h \
		../../Programs/anaconda3/include/qt/QtCore/qdatastream.h \
		../../Programs/anaconda3/include/qt/QtCore/qline.h \
		../../Programs/anaconda3/include/qt/QtGui/qtransform.h \
		../../Programs/anaconda3/include/qt/QtGui/qpainterpath.h \
		../../Programs/anaconda3/include/qt/QtGui/qimage.h \
		../../Programs/anaconda3/include/qt/QtGui/qpixelformat.h \
		../../Programs/anaconda3/include/qt/QtGui/qpixmap.h \
		../../Programs/anaconda3/include/qt/QtGui/qfont.h \
		../../Programs/anaconda3/include/qt/QtGui/qfontmetrics.h \
		../../Programs/anaconda3/include/qt/QtGui/qfontinfo.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../../Programs/anaconda3/include/qt/QtGui/qcursor.h \
		../../Programs/anaconda3/include/qt/QtGui/qkeysequence.h \
		../../Programs/anaconda3/include/qt/QtGui/qevent.h \
		../../Programs/anaconda3/include/qt/QtCore/qurl.h \
		../../Programs/anaconda3/include/qt/QtCore/qurlquery.h \
		../../Programs/anaconda3/include/qt/QtCore/qfile.h \
		../../Programs/anaconda3/include/qt/QtCore/qfiledevice.h \
		../../Programs/anaconda3/include/qt/QtGui/qvector2d.h \
		../../Programs/anaconda3/include/qt/QtGui/qtouchdevice.h \
		../../Programs/anaconda3/include/qt/QtWidgets/qtabwidget.h \
		../../Programs/anaconda3/include/qt/QtGui/qicon.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_keycatcher.o: moc_keycatcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keycatcher.o moc_keycatcher.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

